In [118]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
from itertools import cycle, islice
import matplotlib.pyplot as plt
from pandas.plotting import parallel_coordinates

%matplotlib inline

In [119]:
data = pd.read_csv("/content/drive/MyDrive/academic/l4s2/big data/d2.csv")
data.head()

                                                 Url  ...                                         Decription
0  https://ikman.lk//en/ad/suzuki-wagon-r-fz-safe...  ...  ['<p>Dvd, Tv , Reverse camera, Dual Air Bags, ...
1  https://ikman.lk//en/ad/honda-vezel-z-orange-g...  ...  ['<p>HONDA VEZEL Z ORANGE GOLD BATCH CAC-XXXX ...
2  https://ikman.lk//en/ad/honda-fit-gp-5-l-grade...  ...  ['<p>Honda Fit GP 5 , 2014 , L Grade , F/O , A...
3  https://ikman.lk//en/ad/toyota-premio-ex-g-sup...  ...  ['<p>Toyota Premio F EX G Superior', 'Highest ...
4  https://ikman.lk//en/ad/mercedes-benz-cls-350-...  ...  ['<p>FULLY LOADED,AGENT MAINTAINED,SUNROOF,SOU...

[5 rows x 17 columns]

In [120]:
data.shape

(6797, 17)

In [121]:
data.columns

Index(['Url', 'Title', 'Date', 'District', 'Area', 'Price', 'Brand', 'Model',
       'Trim/Edition', 'ModelYear', 'Condition', 'Transmission', 'BodyType',
       'FuelType', 'EngineCapacity', 'Millage', 'Decription'],
      dtype='object')

In [122]:
features = ['District', 'Area', 'Price', 'Brand', 'Model', 
        'Trim/Edition','ModelYear', 'Condition', 'Transmission', 'BodyType','FuelType','EngineCapacity','Millage']

In [123]:
select_df = data[features]

In [124]:
select_df.columns

Index(['District', 'Area', 'Price', 'Brand', 'Model', 'Trim/Edition',
       'ModelYear', 'Condition', 'Transmission', 'BodyType', 'FuelType',
       'EngineCapacity', 'Millage'],
      dtype='object')

In [125]:
select_df

           District     Area     Price  ... FuelType EngineCapacity     Millage
0           Negombo  Gampaha   3200000  ...   Hybrid         650 cc   63,000 km
1     Mount Lavinia  Colombo   5790000  ...   Hybrid       1,500 cc   59,000 km
2             Kotte  Colombo   4450000  ...   Hybrid       1,500 cc   61,000 km
3          Kohuwala  Colombo  11350000  ...   Petrol       1,500 cc    9,000 km
4         Colombo 8  Colombo  27500000  ...   Petrol       2,000 cc    9,400 km
...             ...      ...       ...  ...      ...            ...         ...
6792     Rambukkana  Kegalle    975000  ...   Petrol         800 cc   83,000 km
6793       Kohuwala  Colombo  16500000  ...   Petrol       2,000 cc   40,000 km
6794   Athurugiriya  Colombo   4650000  ...   Petrol       1,000 cc   64,000 km
6795        Kandana  Gampaha   2395000  ...   Petrol       1,300 cc  140,000 km
6796  Boralesgamuwa  Colombo  15850000  ...   Diesel       2,200 cc   21,000 km

[6797 rows x 13 columns]

In [126]:
select_df['Price'] = select_df['Price'].astype(float)
select_df['ModelYear'] = select_df['ModelYear'].astype(int)
# select_df['EngineCapacity'] = select_df['EngineCapacity'].astype(str)
# select_df["EngineCapacity"] = df.EngineCapacity.apply(lambda x: float(x.replace("/cc","").replace("/cc","")))
select_df['EngineCapacity'] = select_df['EngineCapacity'].str.replace(',', '').str.replace(' cc', '').astype(float)
select_df['Millage'] = select_df['Millage'].str.replace(',', '').str.replace(' km', '').astype(float)
# select_df['EngineCapacity'] = select_df['EngineCapacity'].astype(float)
print(select_df)

           District     Area       Price  ... FuelType EngineCapacity   Millage
0           Negombo  Gampaha   3200000.0  ...   Hybrid          650.0   63000.0
1     Mount Lavinia  Colombo   5790000.0  ...   Hybrid         1500.0   59000.0
2             Kotte  Colombo   4450000.0  ...   Hybrid         1500.0   61000.0
3          Kohuwala  Colombo  11350000.0  ...   Petrol         1500.0    9000.0
4         Colombo 8  Colombo  27500000.0  ...   Petrol         2000.0    9400.0
...             ...      ...         ...  ...      ...            ...       ...
6792     Rambukkana  Kegalle    975000.0  ...   Petrol          800.0   83000.0
6793       Kohuwala  Colombo  16500000.0  ...   Petrol         2000.0   40000.0
6794   Athurugiriya  Colombo   4650000.0  ...   Petrol         1000.0   64000.0
6795        Kandana  Gampaha   2395000.0  ...   Petrol         1300.0  140000.0
6796  Boralesgamuwa  Colombo  15850000.0  ...   Diesel         2200.0   21000.0

[6797 rows x 13 columns]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [127]:
select_df.columns

Index(['District', 'Area', 'Price', 'Brand', 'Model', 'Trim/Edition',
       'ModelYear', 'Condition', 'Transmission', 'BodyType', 'FuelType',
       'EngineCapacity', 'Millage'],
      dtype='object')

In [128]:
categorical_cols = ['District', 'Area', 'Brand', 'Model', 'Trim/Edition', 'Condition','Transmission','BodyType','FuelType']

encoded = pd.get_dummies(select_df, columns=categorical_cols, drop_first=True)

In [129]:
select_df = pd.concat([encoded], axis=1)

In [130]:
select_df.head()

        Price  ModelYear  ...  FuelType_Other fuel type  FuelType_Petrol
0   3200000.0       2015  ...                         0                0
1   5790000.0       2014  ...                         0                0
2   4450000.0       2014  ...                         0                0
3  11350000.0       2019  ...                         0                1
4  27500000.0       2018  ...                         0                1

[5 rows x 3887 columns]

In [131]:
X = StandardScaler().fit_transform(select_df)
X

array([[-0.40472682,  0.57912567, -1.19511571, ...,  2.41335807,
        -0.03432749, -1.51588708],
       [-0.08357529,  0.48621789, -0.04710358, ...,  2.41335807,
        -0.03432749, -1.51588708],
       [-0.24973091,  0.48621789, -0.04710358, ...,  2.41335807,
        -0.03432749, -1.51588708],
       ...,
       [-0.22493156,  0.57912567, -0.72240483, ..., -0.41436039,
        -0.03432749,  0.65967974],
       [-0.50454419, -0.07122885, -0.31722408, ..., -0.41436039,
        -0.03432749,  0.65967974],
       [ 1.1638318 ,  0.85784904,  0.89831818, ..., -0.41436039,
        -0.03432749, -1.51588708]])

In [141]:
kmeans = KMeans(n_clusters=3)
model = kmeans.fit(X)
print("model\n", model)

model
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [142]:
centers = model.cluster_centers_
centers

array([[ 1.50482280e+00,  3.00402307e-01,  1.97880019e+00, ...,
        -4.14360393e-01, -3.43274932e-02, -1.51588708e+00],
       [ 1.49258101e-04, -7.23483394e-04,  4.13796399e-04, ...,
         7.17579436e-05,  4.04507210e-05, -1.36441937e-04],
       [-3.59733721e-01,  6.58760922e-01, -6.84009135e-01, ...,
        -1.04006123e-02, -3.43274932e-02,  3.48884484e-01]])

In [143]:
def pd_centers(featuresUsed, centers):
	colNames = list(featuresUsed)
	colNames.append('prediction')

	# Zip with a column called 'prediction' (index)
	Z = [np.append(A, index) for index, A in enumerate(centers)]

	# Convert to pandas data frame for plotting
	P = pd.DataFrame(Z, columns=colNames)
	P['prediction'] = P['prediction'].astype(int)
	return P

In [144]:
# Function that creates Parallel Plots

def parallel_plot(data):
	my_colors = list(islice(cycle(['b', 'r', 'g', 'y', 'k']), None, len(data)))
	plt.figure(figsize=(15,8)).gca().axes.set_ylim([-3,+3])
	parallel_coordinates(data, 'prediction', color = my_colors, marker='o')

In [145]:
P = pd_centers(list(select_df.columns), centers)
P

      Price  ModelYear  ...  FuelType_Petrol  prediction
0  1.504823   0.300402  ...        -1.515887           0
1  0.000149  -0.000723  ...        -0.000136           1
2 -0.359734   0.658761  ...         0.348884           2

[3 rows x 3888 columns]